config/routes.rb
ScreenshatPik::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "pages#home"

  get "pages/home"

  match 'login' => "dashboard#attempt_login", via: [:get, :post]
  match 'logout' => "dashboard#logout", via: [:get, :post]
  match 'dashboard' => "dashboard#index", via: [:get, :post]

  namespace :dashboard do
    get "index"
    get "public"
    get "login"
    get "account_setting"
  end

  resources :screenshots

  resources :users do
    get :delete
    get :new
  end

end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base

  extend FriendlyId
  friendly_id :username, use: :slugged

  # Relationship and Associations
  has_many :screenshots

  attr_accessor :password

  EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, format: EMAIL_REGEX, confirmation: true

  validates_length_of :password, :within => 8..25, :on => :create

  before_save :prepare_hashed_password
  after_save :clear_password

  has_attached_file :avatar, :styles => {:medium => "250x250", :thumb => "100x100", :tiny => "50x50", :wall => "600x600" }, :default_url => "//placehold.it/100/ffffff/ddddddg"
  validates_attachment :avatar, content_type: { content_type: /\Aimage\/.*\Z/ }
  validates_attachment_size :avatar, less_than: 10.megabytes

  scope :named, lambda { |first, last| where(:first_name => first, :last_name => last) }
  scope :male_users, where(gender: 'male')
  scope :female_users, where(gender: 'female')

  # MODEL ACTIONS/FUNCTIONS
  def ordered_screenshot_by_creation
    screenshots.order('created_at DESC')
  end

  def fullname
    return "#{first_name} #{last_name}"
  end

  def self.generate_salt(username="")
    Digest::SHA2.hexdigest("User #{username} will be salted with #{Time.now}")
  end

  def self.encrypt_password(password="", salt="")
    Digest::SHA2.hexdigest("Hashed #{password} with #{salt}")
  end

  def password_match?(password="")
    hashed_password == User.encrypt_password(password, salt)
  end

  def self.authenticate(username="", password="")
    user = User.find_by_username(username)
    if user && user.password_match?(password)
      return user
    else
      return false
    end
  end

  private

  def prepare_hashed_password
    unless password.blank?
      self.salt = User.generate_salt(username) if salt.blank?
      self.hashed_password = User.encrypt_password(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  protect_from_forgery with: :null_session,
                       if: Proc.new { |c| c.request.format =~ %r{application/json} }

  before_action :user_whois, only: [:show, :edit, :update, :destroy]
  before_filter :catch_current_user, except: [:create]

  # GET /users
  # GET /users.json
  def index
    redirect_to root_path
    #@users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@user = User.friendly.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to users_path
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to dashboard_login_path }
        format.json
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      flash[:notice] = 'Account Information successfully updated.'
      respond_to do |format|
        format.html { redirect_to dashboard_account_setting_path }
        format.js
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    redirect_to users_path
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :email, :username, :password, :salt, :about_me, :slug, :avatar)
  end

  def complete_user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :email, :username, :password, :salt, :about_me, :slug, :avatar)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
.div-transparent
  .text--dark-on-white
    .row
      .col-md-12
        %h3.text-left New to ScreenShat? Sign Up!
        = form_for @user do |f|
          %div.text-left
            - if @user.errors.any?
              #error_explanation
                %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
                %ul
                  - @user.errors.full_messages.each do |msg|
                    %li= msg

          %div{class: 'input-group input-group-lg'}
            %span.input-group-addon
            = f.text_field :first_name, class: 'form-control', placeholder: 'Firstname'
          %div{class: 'input-group input-group-lg'}
            %span.input-group-addon
            = f.text_field :last_name, class: 'form-control', placeholder: 'Lastname'
          %div{class: 'input-group input-group-lg'}
            %span.input-group-addon
            = f.text_field :email, class: 'form-control', placeholder: 'Email'
          %div{class: 'input-group input-group-lg'}
            %span.input-group-addon
            = f.text_field :username, class: 'form-control', placeholder: 'Username'
          %div{class: 'input-group input-group-lg'}
            %span.input-group-addon
            = f.password_field :password, class: 'form-control', placeholder: 'Password'
          -# if session[:id].present?
          %div.text-left
            = f.label 'Profile picture (optional)'
            = f.file_field :avatar, class: 'form-control'
          .row
            .col-md-4
            .col-md-8=# image_tag @user.avatar.url
          %div.pull-right{class: 'btn-group'}
            = f.submit "Sign Up for ScreenShat!", class: 'btn btn-primary btn-lg signup-button'

app/views/users/_sub_form.html.haml
= form_for @current_user, remote: true do |f|
  %table.img-width-fit
    %tr
      %td Firstname
      %td
        %div{class: 'input-group input-group'}
          %span.input-group-addon
          = f.text_field :first_name, class: 'form-control', placeholder: 'Firstname'
    %tr
      %td Lastname
      %td
        %div{class: 'input-group input-group'}
          %span.input-group-addon
          = f.text_field :last_name, class: 'form-control', placeholder: 'Lastname'
    %tr
      %td Gender
      %td
        %div{class: 'input-group input-group'}
          %span.input-group-addon
          = f.select :gender, %w{Male Female}, {}, class: 'form-control'
    %tr
      %td Email
      %td
        %div{class: 'input-group input-group'}
          %span.input-group-addon
          = f.text_field :email, class: 'form-control', placeholder: 'Email'
    %tr
      %td About Me
      %td
        %div{class: 'input-group input-group'}
          %span.input-group-addon
          = f.text_area :about_me, class: 'form-control'
    %tr
      %td Username
      %td
        %div{class: 'input-group input-group'}
          %span.input-group-addon
          = f.text_field :username, class: 'form-control', placeholder: 'Username'
    %tr
      %td Password
      %td
        %div{class: 'input-group input-group'}
          %span.input-group-addon
          = f.password_field :password, class: 'form-control', placeholder: 'Password'
    %tr
      %td
      %td= image_tag @current_user.avatar? ? @current_user.avatar.url(:tiny) : '//placehold.it/100x100'
    %tr
      %td Profile Picture
      %td
        %div.text-left
          = f.label 'Profile picture (optional)'
          = f.file_field :avatar, class: 'form-control'
    %tr
      %td &nbsp;
      %td
        #error_messages
    %tr
      %td &nbsp;
      %td= f.submit "Save", class: 'btn btn-primary form-control', id: 'update-user-info'

:javascript
  $('#update-user-info').on('focus', function() {
    $("#error_messages").text("");
  })

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
.section--container-top#section--carousel-no-bg
  .container
    %h1 Listing users

    %table.table.table-responsive
      %thead
        %tr
          %th Avatar
          %th First name
          %th Last name
          %th Gender
          %th Email
          %th Username
          %th About me
          %th
          %th
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= image_tag user.avatar.url(:thumb), style: 'margin: 2px;'
            %td= user.first_name
            %td= user.last_name
            %td= user.gender
            %td= user.email
            %td= user.username
            %td= user.about_me
            %td= link_to 'Show', user
            %td=# link_to 'Edit', edit_user_path(user)
            %td=# link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New User', new_user_path

app/views/users/new.html.haml
.section--container-top#section--carousel

  .container

    .col-md-6
      .text--white-on-dark
        %h1.text-title-generic.text-center
          %strong.text-with-shadow Welcome to ScreenShat
        %h4.text-subtitle.text-center
          .text-light.text-with-shadow Capture and Share your screenshot moments. Screenshat is a fast, beautiful and fun way to share your screenshots with friends and loved ones.


          = render 'form'

          =# link_to 'Backds', users_path

app/views/users/show.html.haml
.section--container-top#section--carousel
  -# %div{style: 'position: fixed; margin-top: -50px; background: #FFF; opacity: 0.5; height: 100%; width: 100%;'}
    fd
  .container

    .col-lg-3

      .dashboard--section-container
        .generic-image-container
          = image_tag @user.avatar? ? @user.avatar.url(:medium) : '//placehold.it/250/ffffff/dddddd', class: 'img-width-fit'

        #screencaster= @user.fullname
        %table.table.table-hover
          %tr
            %td Email:
            %td= @user.email
          %tr
            %td Username:
            %td= @user.username.titlecase
          %tr
            %td Gender:
            %td= @user.gender
          %tr
            %td About Me:
            %td= @user.about_me
          %tr
            %td Member Since:
            %td= @user.created_at.to_formatted_s(:short)
          %tr
            %td Posts:
            %td= @user.screenshots.count

    .col-lg-6

      #user-screenshots
        - @user.ordered_screenshot_by_creation.each do |screenshot|
          .dashboard--section-container
            .screenshot-container
              #screenshot-image= image_tag screenshot.image.url, class: 'img-ctr'
              #screenshot-description= screenshot.description
              #screenshot-status
                = link_to "Like", '#'
                = "&nbsp;.&nbsp;".html_safe
                = link_to "Comment", '#'
                = "&nbsp;.&nbsp;".html_safe
                = link_to "Share", '#'
                .pull-right= screenshot.created_at.to_formatted_s(:long)
    .col-lg-3
      .dashboard--section-container
        Advetisements

:javascript
  $('#hide_new_screenshot').hide();

app/views/users/update.js.haml
$('#account-setting--user-info').hide();
$('#account-setting--user-info').show();
$("#error_messages").text("#{flash[:notice]}")