config/routes.rb
ScreenshatPik::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "pages#home"

  get "pages/home"

  match 'login' => "dashboard#attempt_login", via: [:get, :post]
  match 'logout' => "dashboard#logout", via: [:get, :post]
  match 'dashboard' => "dashboard#index", via: [:get, :post]

  namespace :dashboard do
    get "index"
    get "public"
    get "login"
    get "account_setting"
  end

  resources :screenshots

  resources :users do
    get :delete
    get :new
  end

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base

  # Relationship and Associations
  belongs_to :user

  has_attached_file :image, :styles => {:medium => "300x300", :thumb => "100x100", :tiny => "50x50", :wall => "600x600" }, :default_url => "//placehold.it/50/ffffff/ddddddg"
  validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
  validates_attachment_size :image, less_than: 10.megabytes
  #validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  validate :check_screenshot_validations

  private

  def check_screenshot_validations
    if !(description.blank? ^ image.blank?) && (description.blank? && image.blank?)
      errors.add(:base, "Description or image can't be null.")
    end
  end

end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController

  protect_from_forgery with: :null_session,
                       if: Proc.new { |c| c.request.format =~ %r{application/json} }

  before_filter :confirm_user_authenticity, :catch_current_user
  before_action :set_screenshot, only: [:show, :edit, :update, :destroy]

  # GET /screenshots
  # GET /screenshots.json
  def index
    redirect_to root_path
    #@screenshots = Screenshot.all
  end

  # GET /screenshots/1
  # GET /screenshots/1.json
  def show
    #@user = User.find(session[:id])
    @screenshot = Screenshot.find(params[:id])
    #redirect_to dashboard_index_path
  end

  # GET /screenshots/new
  def new
    @screenshot = Screenshot.new
    @user = User.find(session[:id])
  end

  # GET /screenshots/1/edit
  def edit
    @user = User.find(session[:id])
  end

  # POST /screenshots
  # POST /screenshots.json
  def create
    @screenshot = Screenshot.new(screenshot_params)
    if @screenshot.valid?
      @current_user.screenshots << @screenshot
      flash[:notice] = "Screenshot was successfully created."
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  # PATCH/PUT /screenshots/1
  # PATCH/PUT /screenshots/1.json
  def update
    respond_to do |format|
      if @screenshot.update(screenshot_params)
        format.html { redirect_to @screenshot, notice: 'Screenshot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenshots/1
  # DELETE /screenshots/1.json
  def destroy
    @screenshot.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_screenshot
    @screenshot = Screenshot.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def screenshot_params
    params.require(:screenshot).permit(:description, :image, :slug)
  end

end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

app/views/screenshots/_form.html.haml
.new_screenshot-container
  .form
    .form-group
      = form_for @screenshot, remote: true do |f|
        - if @screenshot.errors.any?
          #error_explanation
            %h2= "#{pluralize(@screenshot.errors.count, "error")} prohibited this screenshot from being saved:"
            %ul
              - @screenshot.errors.full_messages.each do |msg|
                %li= msg

        .text-left= f.label :description
        .input-group
          .input-group-addon
          = f.text_area :description, class: 'form-control obj-no-resize'
        .form-group-inline
          .text-left= f.label :image
          .input-group
            .input-group-addon
            = f.file_field :image, class: 'form-control'

          .actions
            = f.submit 'Save', class: 'btn btn-primary marginized-top', id: 'save-new-screenshot'

app/views/screenshots/_list.html.haml
%table.table.table-hover

  - @current_user.screenshots.each do |screenshot|
    %tr
      %td= image_tag screenshot.image.url(:tiny)
      %td= screenshot.description
      %td= screenshot.slug
      %td
        = link_to 'Show', screenshot
        = link_to 'Edit', edit_screenshot_path(screenshot)
        = link_to 'Destroy', screenshot, :method => :delete, :data => { :confirm => 'Are you sure?' }, remote: true

app/views/screenshots/create.js.haml
$('#new_screenshot').show();
$('#hide_new_screenshot').hide();
$('#user-screenshots').append("#{ j render(@screenshot)} ")

app/views/screenshots/destroy.js.haml
$('#account-setting--screenshots').hide().after("#{ j render partial: 'screenshots/list' }");
$('#screenshot-counter').text("Screenshots created: #{@current_user.screenshots.count}");

app/views/screenshots/edit.html.haml
.section--container-top#section--carousel
  .container
    %h1 Editing screenshot

    = render 'form'

    = link_to 'Show', @screenshot
    \|
    = link_to 'Back', screenshots_path

app/views/screenshots/index.html.haml
.section--container-top#section--carousel
  .container
    %h1 Listing screenshots

    %table
      %tr
        %th Image
        %th Description
        %th Slug
        %th
        %th
        %th

      - @screenshots.each do |screenshot|
        %tr
          %td= image_tag screenshot.image.url(:tiny)
          %td= screenshot.description
          %td= screenshot.slug
          %td= link_to 'Show', screenshot
          %td= link_to 'Edit', edit_screenshot_path(screenshot)
          %td= link_to 'Destroy', screenshot, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Screenshot', new_screenshot_path

app/views/screenshots/new.html.haml
.section--container-top#section--carousel
  .container
    %h1 New screenshot

    = render 'form'

    = link_to 'Back', screenshots_path

app/views/screenshots/new.js.haml
$('#new_screenshot').hide().after("#{ j render partial: 'screenshots/form'}");
$('#hide_new_screenshot').show();

app/views/screenshots/show.html.haml
.section--container-top#section--carousel
  .container
    %p#notice= notice

    %p
      %b Description:
      = @screenshot.description
    %p
      %b Image:
      = image_tag @screenshot.image.url(:medium)
    %p
      %b Slug:
      = @screenshot.slug

    = link_to 'Edit', edit_screenshot_path(@screenshot)
    \|
    = link_to 'Back', screenshots_path
    = social_share_button_tag(@screenshot.description, path: screenshot_url(@screenshot), image: @screenshot.image.url, desc: @screenshot.description)