config/routes.rb
ScreenshatPik::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "pages#home"

  get "pages/home"

  match 'login' => "dashboard#attempt_login", via: [:get, :post]
  match 'logout' => "dashboard#logout", via: [:get, :post]
  match 'dashboard' => "dashboard#index", via: [:get, :post]

  namespace :dashboard do
    get "index"
    get "public"
    get "login"
    get "account_setting"
  end

  resources :screenshots

  resources :users do
    get :delete
    get :new
  end

end

app/views/layouts/_footer.html.haml
.section--container#section--footer
  .section--sponsors
    .container
      .text--white-on-dark
        .col-md-4
          .row
            .col-md-6
              %h3.text-right
                %strong About ScreenShat
              .text-right
                %p= link_to 'About Us', '#'
                %p= link_to 'Why Us', '#'
                %p= link_to 'Privacy Policy', '#'
                %p= link_to 'Terms and Conditions', '#'
            .col-md-6
              %h3.text-right
                %strong Help & Support
              .text-right
                %p= link_to 'How It Works', '#'
                %p= link_to 'FAQ', '#'
                %p= link_to 'Others', '#'
        .col-md-4
          %h3.text-center
            %strong Featured On
            .row
              %a{href: '#'}
                %i.fa.fa-4x.fa-windows
              %a{href: '#'}
                %i.fa.fa-4x.fa-linux
              %a{href: '#'}
                %i.fa.fa-4x.fa-apple
        .col-md-4
          %h3.text-center
            %strong Social Media
            .row
              %a{href: '#'}
                %i.fa.fa-2x.fa-facebook-square
              %a{href: '#'}
                %i.fa.fa-2x.fa-twitter-square
              %a{href: '#'}
                %i.fa.fa-2x.fa-instagram
              %a{href: '#'}
                %i.fa.fa-2x.fa-linkedin-square
              %a{href: '#'}
                %i.fa.fa-2x.fa-google-plus-square
  .container
    .row
      .text--white-on-dark

        %h5.text-center Copyright 2014. All 'lefts' reserved.

app/views/layouts/_top_bar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}

  .container

    .container-fluid

      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          = image_tag 'sample-logo.png', size: '30x30'
          ScreenShat

      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        - if !session[:id].present?
          %ul.nav.navbar-nav
            %li
              %a{href: "#section--how-it-works"} How It Works
            %li
              %a{href: "#section--featured-screenshots"} Featured Screenshots

            =# render partial: 'layouts/top_bar_dropdown'

          =# render partial: 'layouts/top_bar_search'

        = render partial: 'layouts/top_bar_login_links'

app/views/layouts/_top_bar_dropdown.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    Dropdown
    %span.caret
  %ul.dropdown-menu{:role => "menu"}
    %li
      %a{:href => "#"} Action
    %li
      %a{:href => "#"} Another action
    %li
      %a{:href => "#"} Something else here
    %li.divider
    %li
      %a{:href => "#"} Separated link
    %li.divider
    %li
      %a{:href => "#"} One more separated link

app/views/layouts/_top_bar_login_links.html.haml
%ul.nav.navbar-nav.navbar-right
  - if session[:id].present?
    %li= link_to "Welcome, #{@current_user.username.titlecase}!", dashboard_path
    %li= link_to "Account Settings", dashboard_account_setting_path
    %li= link_to 'Logout', { controller: :dashboard, action: :logout }
  - else
    %li= link_to 'Sign In', dashboard_login_path

app/views/layouts/_top_bar_search.html.haml
%form.navbar-form.navbar-left{:role => "search"}
  .form-group
    %input.form-control{:placeholder => "Search", :type => "text"}/
  %button.btn.btn-default{:type => "submit"} Submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Screenshat
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    = render partial: 'layouts/top_bar'
    = yield
    = render partial: 'layouts/footer'